param(
    [ValidateSet("Start", "Stop", "Status", "Restart", "InstallShortcuts")]
    [string]$Action = "Start",
    [int]$BackendPort = 8000,
    [int]$FrontendPort = 5174,
    [switch]$Visible,
    [switch]$Quiet
)

$ErrorActionPreference = "Stop"

$RepoRoot = Resolve-Path (Join-Path $PSScriptRoot "..")
$BackendDir = Join-Path $RepoRoot "backend"
$FrontendDir = Join-Path $RepoRoot "frontend"
$BackendPython = Join-Path $BackendDir "venv\Scripts\python.exe"
$IconSource = Join-Path $RepoRoot "logo.png"
$IconDir = Join-Path $FrontendDir "resources"
$IconPath = Join-Path $IconDir "project-r.ico"
$LogDir = Join-Path $BackendDir "logs\dev-launcher"
$BackendLog = Join-Path $LogDir "backend.log"
$BackendErrorLog = Join-Path $LogDir "backend-error.log"
$FrontendLog = Join-Path $LogDir "frontend.log"
$FrontendErrorLog = Join-Path $LogDir "frontend-error.log"
$LauncherLog = Join-Path $LogDir "launcher.log"
$StateFile = Join-Path $LogDir "state.json"

$RepoPattern = [regex]::Escape($RepoRoot.Path)
$BackendPattern = [regex]::Escape($BackendDir)
$FrontendPattern = [regex]::Escape($FrontendDir)
$script:LastStopWarnings = @()

function Join-Chars {
    param([int[]]$CodePoints)
    return -join ($CodePoints | ForEach-Object { [char]$_ })
}

function Quote-PS {
    param([string]$Value)
    return "'" + ($Value -replace "'", "''") + "'"
}

function Write-LauncherLog {
    param([string]$Message)
    New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
    $line = "[{0}] {1}" -f (Get-Date -Format "yyyy-MM-dd HH:mm:ss"), $Message
    Add-Content -LiteralPath $LauncherLog -Value $line -Encoding UTF8
}

function Show-LauncherMessage {
    param(
        [string]$Title,
        [string]$Message,
        [string]$Icon = "Information"
    )

    Write-Host ""
    Write-Host $Title
    Write-Host $Message

    if ($Quiet) {
        return
    }

    try {
        Add-Type -AssemblyName System.Windows.Forms -ErrorAction Stop
        $messageIcon = [System.Windows.Forms.MessageBoxIcon]::$Icon
        [System.Windows.Forms.MessageBox]::Show(
            $Message,
            $Title,
            [System.Windows.Forms.MessageBoxButtons]::OK,
            $messageIcon
        ) | Out-Null
    } catch {
        try {
            $shell = New-Object -ComObject WScript.Shell
            $shell.Popup($Message, 8, $Title, 64) | Out-Null
        } catch {
            Write-Host $Message
        }
    }
}

function Write-ChildScript {
    param(
        [string]$Name,
        [string]$Content
    )

    $childScriptDir = Join-Path $LogDir "scripts"
    New-Item -ItemType Directory -Force -Path $childScriptDir | Out-Null
    $path = Join-Path $childScriptDir $Name
    $script = @(
        "# Auto-generated by Project_R launcher.",
        "# This file is intentionally plain text so security tools and users can inspect it.",
        $Content
    ) -join [Environment]::NewLine
    Set-Content -LiteralPath $path -Value $script -Encoding UTF8
    return $path
}

function Test-ProjectProcess {
    param($Process)

    if (-not $Process.CommandLine) {
        return $false
    }
    if ($Process.ProcessId -eq $PID) {
        return $false
    }

    $commandLine = $Process.CommandLine
    $isLauncherChild = $commandLine -match "PROJECT_R_LAUNCHER"
    $isProjectBackend = $commandLine -match $BackendPattern -and (
        $commandLine -match "uvicorn" -or
        $commandLine -match "main:app"
    )
    $isProjectFrontend = $commandLine -match $FrontendPattern -and (
        $commandLine -match "scripts[\\/]+dev\.mjs" -or
        $commandLine -match "bun(\.exe)?`"?\s+run\s+dev" -or
        $commandLine -match "npm(\.cmd|\.ps1)?`"?\s+run\s+dev" -or
        $commandLine -match "vite" -or
        $commandLine -match "electron"
    )
    $isLegacyBackend = $commandLine -match $RepoPattern -and
        $commandLine -match "backend" -and
        $commandLine -match "uvicorn" -and
        $commandLine -match "main:app"

    return $isLauncherChild -or $isProjectBackend -or $isProjectFrontend -or $isLegacyBackend
}

function Test-PortProcessBelongsToProject {
    param(
        $Process,
        [int]$Port
    )

    if ($Process -and (Test-ProjectProcess $Process)) {
        return $true
    }

    if (
        $Port -eq $FrontendPort -and
        $Process -and
        $Process.Name -eq "bun.exe" -and
        $Process.CommandLine -match "run\s+scripts[\\/]+dev\.mjs"
    ) {
        return $true
    }

    return $false
}

function Get-ProjectProcesses {
    Get-CimInstance Win32_Process | Where-Object { Test-ProjectProcess $_ }
}

function Stop-ProcessSafe {
    param(
        [int]$ProcessId,
        [string]$Reason
    )

    if ($ProcessId -eq 0 -or $ProcessId -eq $PID) {
        return
    }

    $process = Get-Process -Id $ProcessId -ErrorAction SilentlyContinue
    if (-not $process) {
        return
    }

    Write-LauncherLog "Stopping PID $ProcessId ($($process.ProcessName)): $Reason"
    Stop-Process -Id $ProcessId -Force -ErrorAction SilentlyContinue
}

function Stop-ProjectDevProcesses {
    foreach ($pass in 1..3) {
        $processes = @(Get-ProjectProcesses)
        if ($processes.Count -eq 0) {
            return
        }
        foreach ($process in $processes) {
            Stop-ProcessSafe -ProcessId $process.ProcessId -Reason "Project_R dev process"
        }
        Start-Sleep -Milliseconds 400
    }
}

function Get-PortListeners {
    param([int]$Port)
    @(Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue)
}

function Clear-ProjectPort {
    param([int]$Port)

    $listeners = Get-PortListeners -Port $Port
    foreach ($listener in $listeners) {
        $process = Get-CimInstance Win32_Process -Filter "ProcessId = $($listener.OwningProcess)" -ErrorAction SilentlyContinue
        if ($process -and (Test-PortProcessBelongsToProject -Process $process -Port $Port)) {
            Stop-ProcessSafe -ProcessId $listener.OwningProcess -Reason "listening on Project_R port $Port"
            continue
        }

        $name = if ($process) { $process.Name } else { "unknown" }
        throw "Port $Port is occupied by a non-Project_R process: PID $($listener.OwningProcess) $name"
    }
}

function Wait-PortFree {
    param(
        [int]$Port,
        [int]$TimeoutSeconds = 10
    )

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        if ((Get-PortListeners -Port $Port).Count -eq 0) {
            return
        }
        Start-Sleep -Milliseconds 300
    }

    throw "Port $Port is still occupied after cleanup."
}

function Test-HttpOk {
    param([string]$Url)

    try {
        $response = Invoke-WebRequest -Uri $Url -Method Get -UseBasicParsing -TimeoutSec 3
        return $response.StatusCode -ge 200 -and $response.StatusCode -lt 500
    } catch {
        return $false
    }
}

function Test-ProjectBackendService {
    param([int]$Port)

    try {
        $health = Invoke-RestMethod -Uri "http://127.0.0.1:$Port/health" -Method Get -TimeoutSec 3
        if (-not $health -or $health.status -ne "ok") {
            return $false
        }
        Invoke-WebRequest -Uri "http://127.0.0.1:$Port/health/llm" -Method Get -UseBasicParsing -TimeoutSec 3 | Out-Null
        return $true
    } catch {
        return $false
    }
}

function Wait-HttpOk {
    param(
        [string]$Url,
        [int]$TimeoutSeconds = 60
    )

    $deadline = (Get-Date).AddSeconds($TimeoutSeconds)
    while ((Get-Date) -lt $deadline) {
        if (Test-HttpOk -Url $Url) {
            return
        }
        Start-Sleep -Milliseconds 500
    }

    throw "Service did not become ready: $Url"
}

function Get-PortStatusText {
    param(
        [string]$Name,
        [int]$Port,
        [string]$HealthUrl = ""
    )

    $listeners = Get-PortListeners -Port $Port
    if ($listeners.Count -eq 0) {
        return "$Name 127.0.0.1:$Port - not listening"
    }

    $lines = @()
    foreach ($listener in $listeners) {
        $process = Get-CimInstance Win32_Process -Filter "ProcessId = $($listener.OwningProcess)" -ErrorAction SilentlyContinue
        $processName = if ($process) { $process.Name } else { "unknown" }
        $scope = if ($process -and (Test-PortProcessBelongsToProject -Process $process -Port $Port)) {
            "Project_R"
        } elseif (-not $process -and $Port -eq $BackendPort -and (Test-ProjectBackendService -Port $Port)) {
            "Project_R service, process unavailable"
        } else {
            "other app"
        }
        $lines += "$Name 127.0.0.1:$Port - PID $($listener.OwningProcess) $processName ($scope)"
    }

    if ($HealthUrl) {
        $health = if (Test-HttpOk -Url $HealthUrl) { "OK" } else { "failed" }
        $lines += "$Name health - $health"
    }

    return ($lines -join [Environment]::NewLine)
}

function Get-PrimaryIPv4 {
    try {
        $route = Get-NetRoute -DestinationPrefix "0.0.0.0/0" |
            Sort-Object RouteMetric, InterfaceMetric |
            Select-Object -First 1
        if ($null -eq $route) {
            return $null
        }
        $address = Get-NetIPAddress -AddressFamily IPv4 -InterfaceIndex $route.InterfaceIndex |
            Where-Object { $_.IPAddress -notlike "169.254.*" -and $_.IPAddress -ne "127.0.0.1" } |
            Select-Object -First 1
        return $address.IPAddress
    } catch {
        return $null
    }
}

function Add-ProjectRFirewallRule {
    param([int]$Port)

    $identity = [Security.Principal.WindowsIdentity]::GetCurrent()
    $principal = [Security.Principal.WindowsPrincipal]::new($identity)
    $isAdmin = $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)

    if (-not $isAdmin) {
        Write-LauncherLog "Firewall rule not added: not running as Administrator."
        Write-Host "Firewall rule not added (not Admin). Run as Administrator to auto-add firewall rule." -ForegroundColor Yellow
        return
    }

    $ruleName = "Project_R Backend LAN ($Port)"
    try {
        $existingRule = Get-NetFirewallRule -DisplayName $ruleName -ErrorAction Stop
        if ($null -eq $existingRule) {
            New-NetFirewallRule `
                -DisplayName $ruleName `
                -Direction Inbound `
                -Action Allow `
                -Protocol TCP `
                -LocalPort $Port `
                -Profile Private | Out-Null
            Write-LauncherLog "Added firewall rule: $ruleName"
            Write-Host "Added firewall rule: $ruleName" -ForegroundColor Green
        } else {
            Write-LauncherLog "Firewall rule already exists: $ruleName"
            Write-Host "Firewall rule already exists: $ruleName" -ForegroundColor Yellow
        }
    } catch {
        Write-LauncherLog "Firewall cmdlet unavailable (NetSecurity module missing): $_"
        Write-Host "Firewall rule not checked (NetSecurity module unavailable)." -ForegroundColor Yellow
    }
}

function Assert-DevDependencies {
    if (-not (Test-Path $BackendDir)) {
        throw "Backend directory not found: $BackendDir"
    }
    if (-not (Test-Path $FrontendDir)) {
        throw "Frontend directory not found: $FrontendDir"
    }
    if (-not (Test-Path $BackendPython)) {
        throw "Backend venv python not found: $BackendPython"
    }
    if (-not (Test-Path (Join-Path $FrontendDir "node_modules"))) {
        throw "Frontend node_modules not found. Run 'bun install' in frontend first."
    }
    $bun = Get-Command bun.exe -ErrorAction SilentlyContinue
    if (-not $bun) {
        $bun = Get-Command bun -ErrorAction SilentlyContinue
    }
    if (-not $bun) {
        throw "Bun was not found in PATH."
    }
    return $bun.Source
}

function Convert-PngToIco {
    param(
        [string]$SourcePng,
        [string]$TargetIco
    )

    if (-not (Test-Path $SourcePng)) {
        throw "Icon source not found: $SourcePng"
    }

    Add-Type -AssemblyName System.Drawing
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $TargetIco) | Out-Null

    $sizes = @(16, 24, 32, 48, 64, 128, 256)
    $image = [System.Drawing.Image]::FromFile((Resolve-Path $SourcePng).Path)
    $entries = New-Object System.Collections.Generic.List[object]

    try {
        foreach ($size in $sizes) {
            $pixelFormat = [System.Drawing.Imaging.PixelFormat]::Format32bppArgb
            $bitmap = New-Object System.Drawing.Bitmap -ArgumentList $size, $size, $pixelFormat
            $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
            $stream = New-Object System.IO.MemoryStream
            try {
                $graphics.Clear([System.Drawing.Color]::Transparent)
                $graphics.CompositingQuality = [System.Drawing.Drawing2D.CompositingQuality]::HighQuality
                $graphics.InterpolationMode = [System.Drawing.Drawing2D.InterpolationMode]::HighQualityBicubic
                $graphics.SmoothingMode = [System.Drawing.Drawing2D.SmoothingMode]::HighQuality

                $scale = [Math]::Min($size / $image.Width, $size / $image.Height)
                $width = [Math]::Max(1, [int][Math]::Round($image.Width * $scale))
                $height = [Math]::Max(1, [int][Math]::Round($image.Height * $scale))
                $x = [int][Math]::Floor(($size - $width) / 2)
                $y = [int][Math]::Floor(($size - $height) / 2)
                $graphics.DrawImage($image, $x, $y, $width, $height)
                $bitmap.Save($stream, [System.Drawing.Imaging.ImageFormat]::Png)
                $entries.Add([pscustomobject]@{
                    Size = $size
                    Bytes = $stream.ToArray()
                })
            } finally {
                $stream.Dispose()
                $graphics.Dispose()
                $bitmap.Dispose()
            }
        }
    } finally {
        $image.Dispose()
    }

    $output = [System.IO.File]::Open($TargetIco, [System.IO.FileMode]::Create)
    $writer = New-Object System.IO.BinaryWriter($output)
    try {
        $writer.Write([UInt16]0)
        $writer.Write([UInt16]1)
        $writer.Write([UInt16]$entries.Count)

        $offset = 6 + (16 * $entries.Count)
        foreach ($entry in $entries) {
            $sizeByte = if ($entry.Size -eq 256) { 0 } else { $entry.Size }
            $writer.Write([byte]$sizeByte)
            $writer.Write([byte]$sizeByte)
            $writer.Write([byte]0)
            $writer.Write([byte]0)
            $writer.Write([UInt16]1)
            $writer.Write([UInt16]32)
            $writer.Write([UInt32]$entry.Bytes.Length)
            $writer.Write([UInt32]$offset)
            $offset += $entry.Bytes.Length
        }

        foreach ($entry in $entries) {
            $writer.Write([byte[]]$entry.Bytes)
        }
    } finally {
        $writer.Dispose()
        $output.Dispose()
    }
}

function Ensure-ProjectIcon {
    $needsUpdate = -not (Test-Path $IconPath)
    if (-not $needsUpdate -and (Test-Path $IconSource)) {
        $needsUpdate = (Get-Item $IconSource).LastWriteTimeUtc -gt (Get-Item $IconPath).LastWriteTimeUtc
    }

    if ($needsUpdate) {
        Convert-PngToIco -SourcePng $IconSource -TargetIco $IconPath
        Write-LauncherLog "Generated icon: $IconPath"
    }
}

function Start-ProjectR {
    $bunPath = Assert-DevDependencies
    New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
    "" | Set-Content -LiteralPath $BackendLog -Encoding UTF8
    "" | Set-Content -LiteralPath $BackendErrorLog -Encoding UTF8
    "" | Set-Content -LiteralPath $FrontendLog -Encoding UTF8
    "" | Set-Content -LiteralPath $FrontendErrorLog -Encoding UTF8

    Write-LauncherLog "Starting Project_R"
    Add-ProjectRFirewallRule -Port $BackendPort
    Stop-ProjectDevProcesses
    $reuseBackend = $false
    try {
        Clear-ProjectPort -Port $BackendPort
    } catch {
        if (Test-ProjectBackendService -Port $BackendPort) {
            $reuseBackend = $true
            Write-LauncherLog "Reusing existing healthy Project_R backend on port $BackendPort because the OS did not expose a killable process."
        } else {
            throw
        }
    }
    Clear-ProjectPort -Port $FrontendPort
    if (-not $reuseBackend) {
        Wait-PortFree -Port $BackendPort
    }
    Wait-PortFree -Port $FrontendPort

    $backendCommand = @(
        "`$ErrorActionPreference = 'Stop'",
        "`$env:PROJECT_R_LAUNCHER = '1'",
        "Set-Location -LiteralPath $(Quote-PS $BackendDir)",
        "& $(Quote-PS $BackendPython) -m uvicorn main:app --reload --host 0.0.0.0 --port $BackendPort"
    ) -join "; "
    $frontendCommand = @(
        "`$ErrorActionPreference = 'Stop'",
        "`$env:PROJECT_R_LAUNCHER = '1'",
        "`$env:PROJECT_R_FRONTEND_PORT = '$FrontendPort'",
        "`$env:PROJECT_R_STRICT_FRONTEND_PORT = '1'",
        "Set-Location -LiteralPath $(Quote-PS $FrontendDir)",
        "& $(Quote-PS $bunPath) run dev"
    ) -join "; "
    $backendScript = Write-ChildScript -Name "start-backend.ps1" -Content $backendCommand
    $frontendScript = Write-ChildScript -Name "start-frontend.ps1" -Content $frontendCommand

    $windowStyle = if ($Visible) { "Normal" } else { "Minimized" }
    $backendProcess = $null
    if (-not $reuseBackend) {
        $backendProcess = Start-Process powershell.exe -ArgumentList @(
            "-NoProfile",
            "-ExecutionPolicy", "Bypass",
            "-File", $backendScript
        ) -WorkingDirectory $BackendDir -WindowStyle $windowStyle -RedirectStandardOutput $BackendLog -RedirectStandardError $BackendErrorLog -PassThru
    }

    Wait-HttpOk -Url "http://127.0.0.1:$BackendPort/health" -TimeoutSeconds 60

    $frontendProcess = Start-Process powershell.exe -ArgumentList @(
        "-NoProfile",
        "-ExecutionPolicy", "Bypass",
        "-File", $frontendScript
    ) -WorkingDirectory $FrontendDir -WindowStyle $windowStyle -RedirectStandardOutput $FrontendLog -RedirectStandardError $FrontendErrorLog -PassThru

    Wait-HttpOk -Url "http://127.0.0.1:$FrontendPort/" -TimeoutSeconds 90

    [pscustomobject]@{
        startedAt = (Get-Date).ToString("o")
        backendPort = $BackendPort
        frontendPort = $FrontendPort
        backendLauncherPid = if ($backendProcess) { $backendProcess.Id } else { $null }
        frontendLauncherPid = $frontendProcess.Id
        backendLog = $BackendLog
        backendErrorLog = $BackendErrorLog
        frontendLog = $FrontendLog
        frontendErrorLog = $FrontendErrorLog
    } | ConvertTo-Json -Depth 3 | Set-Content -LiteralPath $StateFile -Encoding UTF8

    $backendPidText = if ($backendProcess) { [string]$backendProcess.Id } else { "reused existing service" }
    $lanIp = Get-PrimaryIPv4
    $lanUrl = if ($lanIp) { "http://$lanIp`:$BackendPort" } else { "LAN IP not detected" }
    Write-LauncherLog "Project_R started. Backend launcher PID $backendPidText, frontend launcher PID $($frontendProcess.Id), LAN $lanUrl"
    Write-Host "Project_R started."

    if ($lanIp) {
        Show-LauncherMessage -Title "Project_R 已启动" -Message "后端 (本机): http://127.0.0.1:$BackendPort`n前端 (本机): http://127.0.0.1:$FrontendPort`n`n局域网访问: $lanUrl"
    } else {
        Show-LauncherMessage -Title "Project_R 已启动" -Message "后端 (本机): http://127.0.0.1:$BackendPort`n前端 (本机): http://127.0.0.1:$FrontendPort`n`n未能检测到局域网IP，请在终端运行 ipconfig 获取地址"
    }
}

function Stop-ProjectR {
    Write-LauncherLog "Stopping Project_R"
    $script:LastStopWarnings = @()
    Stop-ProjectDevProcesses

    Clear-ProjectPort -Port $FrontendPort
    Wait-PortFree -Port $FrontendPort

    try {
        Clear-ProjectPort -Port $BackendPort
        Wait-PortFree -Port $BackendPort
    } catch {
        if (Test-ProjectBackendService -Port $BackendPort) {
            $warning = "Backend port $BackendPort still has a healthy Project_R service, but Windows does not expose a killable process for it."
            $script:LastStopWarnings += $warning
            Write-LauncherLog $warning
        } else {
            throw
        }
    }
    Write-LauncherLog "Project_R stopped"
}

function Show-ProjectStatus {
    New-Item -ItemType Directory -Force -Path $LogDir | Out-Null

    $backendHealthy = Test-ProjectBackendService -Port $BackendPort
    $backendListening = (Get-PortListeners -Port $BackendPort).Count -gt 0
    $frontendListening = (Get-PortListeners -Port $FrontendPort).Count -gt 0
    $frontendHealthy = if ($frontendListening) { Test-HttpOk -Url "http://127.0.0.1:$FrontendPort/" } else { $false }
    $lanIp = Get-PrimaryIPv4
    $lanUrl = if ($lanIp) { "http://$lanIp`:$BackendPort" } else { "" }
    $firewallRuleName = "Project_R Backend LAN ($BackendPort)"
    $firewallExists = $false
    try {
        $firewallExists = $null -ne (Get-NetFirewallRule -DisplayName $firewallRuleName -ErrorAction Stop)
    } catch {
        $firewallExists = $false
    }

    $llmConfigured = $null
    $gbrainOk = $null
    if ($backendHealthy) {
        try { $llmConfigured = (Invoke-RestMethod -Uri "http://127.0.0.1:$BackendPort/health/llm" -TimeoutSec 3).configured } catch { $llmConfigured = $false }
        try { $gbrainOk = (Invoke-RestMethod -Uri "http://127.0.0.1:$BackendPort/health/gbrain" -TimeoutSec 3).ok } catch { $gbrainOk = $false }
    }

    function DotColor { param($C) if ($C -eq $true) { return "#22c55e" } if ($C -eq $false) { return "#ef4444" } return "#9ca3af" }
    function StatRow { param($L, $C, $Ok, $Fail) $color = DotColor $C; $txt = if ($C -eq $true) { $Ok } elseif ($C -eq $false) { $Fail } else { "等待检测..." }; return "<div class='r'><span class='d' style='background:$color'></span><span class='l'>$L</span><span class='v'>$txt</span></div>" }

    $now = Get-Date -Format 'HH:mm:ss'
    $rows = @(
        (StatRow "后端服务" $backendHealthy "运行正常 (端口 $BackendPort)" $(if ($backendListening) { "端口占用但健康检查失败" } else { "未运行" })),
        (StatRow "前端服务" $frontendHealthy "运行正常 (端口 $FrontendPort)" $(if ($frontendListening) { "端口占用但页面无响应" } else { "未运行" })),
        (StatRow "局域网访问" ([bool]$lanIp) "<code>$lanUrl</code>" "未检测到局域网IP"),
        (StatRow "防火墙规则" $firewallExists "入站规则已添加" "未添加 (非管理员无法自动添加)"),
        (StatRow "LLM 供应商" $llmConfigured "已配置" $(if ($null -eq $llmConfigured) { "后端未运行" } else { "未配置或不可用" })),
        (StatRow "GBrain 知识库" $gbrainOk "就绪" $(if ($null -eq $gbrainOk) { "后端未运行" } else { "不可用" }))
    )

    $html = @"
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta http-equiv="refresh" content="10">
<title>Project_R 服务状态</title>
<style>
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,'Microsoft YaHei','PingFang SC',sans-serif;max-width:620px;margin:40px auto;padding:0 16px;background:#f0f2f5}
.c{background:#fff;border-radius:12px;padding:24px;margin-bottom:16px;box-shadow:0 1px 3px rgba(0,0,0,.08)}
h1{font-size:22px;font-weight:700;margin-bottom:4px}
.s{color:#888;font-size:13px;margin-bottom:20px}
.r{display:flex;align-items:center;padding:12px 8px;border-bottom:1px solid #f3f4f6}
.r:last-child{border-bottom:none}
.d{width:10px;height:10px;border-radius:50%;margin-right:12px;flex-shrink:0}
.l{font-weight:600;font-size:14px;min-width:110px;color:#374151}
.v{color:#6b7280;font-size:14px;word-break:break-all}
.v code{font-family:'SF Mono',Consolas,monospace;color:#2563eb;font-size:13px}
.f{text-align:center;color:#9ca3af;font-size:12px;margin-top:20px}
</style>
</head>
<body>
<div class="c">
<h1>&#x1F535; Project_R 服务状态</h1>
<p class="s">刷新时间: $now &#183; 每 10 秒自动刷新</p>
$($rows -join "`n")
</div>
<p class="f">Project_R &#183; 状态面板</p>
</body>
</html>
"@

    try {
        $pagePath = Join-Path $LogDir "status.html"
        $html | Set-Content -LiteralPath $pagePath -Encoding UTF8
        Start-Process $pagePath
        Write-LauncherLog "Status page opened in browser: $pagePath"
    } catch {
        Write-LauncherLog "Failed to open status page: $_"
        Show-LauncherMessage -Title "Project_R Status" -Message "无法打开状态页面，请检查浏览器设置。"
    }
}

function Install-ProjectShortcuts {
    Ensure-ProjectIcon

    $desktop = [Environment]::GetFolderPath("DesktopDirectory")
    $shell = New-Object -ComObject WScript.Shell
    $powershell = (Get-Command powershell.exe).Source
    $startName = "Project_R $(Join-Chars @(0x542F, 0x52A8)).lnk"
    $statusName = "Project_R $(Join-Chars @(0x72B6, 0x6001)).lnk"
    $stopName = "Project_R $(Join-Chars @(0x505C, 0x6B62)).lnk"

    $items = @(
        [pscustomobject]@{ Name = $startName; Action = "Start"; Description = "Start Project_R" },
        [pscustomobject]@{ Name = $statusName; Action = "Status"; Description = "Show Project_R status" },
        [pscustomobject]@{ Name = $stopName; Action = "Stop"; Description = "Stop Project_R" }
    )

    foreach ($item in $items) {
        $shortcutPath = Join-Path $desktop $item.Name
        $shortcut = $shell.CreateShortcut($shortcutPath)
        $shortcut.TargetPath = $powershell
        $shortcut.Arguments = "-NoProfile -ExecutionPolicy Bypass -File `"$PSCommandPath`" -Action $($item.Action)"
        $shortcut.WorkingDirectory = $RepoRoot.Path
        $shortcut.IconLocation = "$IconPath,0"
        $shortcut.Description = $item.Description
        $shortcut.WindowStyle = if ($item.Action -eq "Start") { 7 } else { 1 }
        $shortcut.Save()
        if (-not (Test-Path -LiteralPath $shortcutPath)) {
            throw "Shortcut was not created: $shortcutPath"
        }
    }

    $message = @(
        "Desktop shortcuts installed:",
        (Join-Path $desktop $startName),
        (Join-Path $desktop $statusName),
        (Join-Path $desktop $stopName),
        "",
        "提示：启动 (Start) 现已自动开通局域网和防火墙规则。",
        '如果桌面上有旧的"内网端口"快捷方式，可以手动删除。'
    ) -join [Environment]::NewLine
    Show-LauncherMessage -Title "Project_R Shortcuts" -Message $message
}

try {
    switch ($Action) {
        "Start" {
            Start-ProjectR
        }
        "Stop" {
            Stop-ProjectR
            if ($script:LastStopWarnings.Count -gt 0) {
                $message = @(
                    "Project_R frontend/dev processes have been stopped.",
                    "",
                    "Warning:",
                    ($script:LastStopWarnings -join [Environment]::NewLine)
                ) -join [Environment]::NewLine
                Show-LauncherMessage -Title "Project_R Stop" -Message $message -Icon "Warning"
            } else {
                Show-LauncherMessage -Title "Project_R Stop" -Message "Project_R dev processes and ports have been stopped."
            }
        }
        "Status" {
            Show-ProjectStatus
        }
        "Restart" {
            Stop-ProjectR
            Start-ProjectR
        }
        "InstallShortcuts" {
            Install-ProjectShortcuts
        }
    }
} catch {
    $message = @(
        "Action failed: $Action",
        $_.Exception.Message,
        "",
        "Logs:",
        $BackendLog,
        $BackendErrorLog,
        $FrontendLog,
        $FrontendErrorLog,
        $LauncherLog
    ) -join [Environment]::NewLine
    Write-LauncherLog $message
    Show-LauncherMessage -Title "Project_R Launcher Error" -Message $message -Icon "Error"
    exit 1
}
